### ISSUE TITLE
npm version has no comments support

### ISSUE THREAD

**Issue by glaidler** [slang800/instagram-screen-scrape#6]
Hi, the js code to get hold of comments isn't in the npm version.  Is this intentional?

G

**Comment by notslang** [comment]
sorry - haven't released 2.0 yet... I'll try to do that later today

**Comment by glaidler** [comment]
No problem thanks. Great bit of kit.  So frustrating what instagram keep hidden.  Do you know if I can get a list of followers from a given user?

**Comment by notslang** [comment]
Published v2! (only 123 "today"s later)

And I haven't written anything for getting the list of followers because Instagram doesn't show that on their website, but if you poke around their undocumented APIs (or use a spoofed security certificate on a mobile device and then decrypted the traffic coming from their app) you could probably find a way to do it... If you do, I'd love to accept a PR for that.
